export default [
  {
    id: 1,
    title: "First Item",
    description: "This is the first item",
    image: "https://source.unsplash.com/random/200x300",
    rating: 4,
    openSpots: 2,
    location: "New York",
    link: "https://goo.gl/maps/BD9g7aujyy8B2JBLA",
    start_date: "2020-01-01",
    end_date: "2022-01-01",
  },
  {
    id: 2,
    title: "Second Item",
    description: "This is the second item",
    image: "https://source.unsplash.com/random/200x300",
    rating: 3,
    openSpots: 1,
    location: "Austin",
    link: "https://goo.gl/maps/Dm3nri7CVLK5TjWM7",
    start_date: "2020-01-01",
    end_date: "2022-01-01",
  },
  {
    id: 3,
    title: "Third Item",
    description: "This is the third item",
    image: "https://source.unsplash.com/random/200x300",
    rating: 5,
    openSpots: 0,
    location: "San Francisco",
    link: "https://goo.gl/maps/Dm3nri7CVLK5TjWM7",
    start_date: "2020-01-01",
    end_date: "2022-01-01",
  },
  {
    id: 4,
    title: "Fourth Item",
    description: "This is the fourth item",
    image: "https://source.unsplash.com/random/200x300",
    rating: 2,
    openSpots: 0,
    location: "Los Angeles",
    link: "https://goo.gl/maps/Dm3nri7CVLK5TjWM7",
    start_date: "2020-01-01",
    end_date: "2022-01-01",
  },
  {
    id: 5,
    title: "Fifth Item",
    description: "This is the fifth item",
    image: "https://source.unsplash.com/random/200x300",
    rating: 1,
    openSpots: 0,
    location: "Seattle",
    link: "https://goo.gl/maps/Dm3nri7CVLK5TjWM7",
    start_date: "2020-01-01",
    end_date: "2022-01-01",
  },
];
